import { ProductSubImg } from './../../entities/product/product.sub.img';
import { Product } from './../../entities/product/product.info';
import { ProductSailInfo } from './../../entities/product/product.sale.info';
import { Users } from './../../entities/users/users.info';
import { Connection } from 'typeorm';
import { Factory, Seeder } from 'typeorm-seeding';

export class CreateInitialData implements Seeder {
  public async run(factory: Factory, connection: Connection): Promise<any> {
    await connection
      .createQueryBuilder()
      .insert()
      .into(Users)
      .values([
        {
          id: 1,
          userId: 'brojoon',
          password: '123123',
          address: '서울시 송파구 송파대로 567 530동 310호',
          email: 'ydngjink1234@gmail.com',
          phone_number: '010-1234-5678',
        },
      ])
      .execute();

    ///// Users

    await connection
      .createQueryBuilder()
      .insert()
      .into(Product)
      .values([
        {
          id: 1,
          code: 'bs4691',
          name: 'bs4691 매끄러운 광택감이 돋보이는 베이직 셔츠',
          type: 'blouse',
          price: 23000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/blouse/bs4691/main.gif',
        },
        {
          id: 2,
          code: 'bs5039',
          name: 'bs5039 찰랑 쫀득한 심플 베이직 오픈카라 블라우스',
          type: 'blouse',
          price: 21000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/blouse/bs5039/main.gif',
        },
        {
          id: 3,
          code: 'bs6704',
          name: 'bs6704 데일리 코튼 셔츠 블라우스',
          type: 'blouse',
          price: 32000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/blouse/bs6704/main.gif',
        },
        {
          id: 4,
          code: 'bs6709',
          name: 'bs6709 하트 버튼 포인트의 절개 디테일 빅카라넥 블라우스',
          type: 'blouse',
          price: 25000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/blouse/bs6709/main.gif',
        },
        {
          id: 5,
          code: 'bs6714',
          name: 'bs6714 랜디스 찰랑폴리 배색 리본 셔링 블라우스',
          type: 'blouse',
          price: 28000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/blouse/bs6714/main.gif',
        },
        {
          id: 6,
          code: 'jk1296',
          name: 'jk1296 브랜드 감성의 아뜨메이드 테일러드카라 싱글 자켓',
          type: 'jacket',
          price: 38000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/jacket/jk1296/main.gif',
        },
        {
          id: 7,
          code: 'jk1442',
          name: 'jk1442 시그니쳐 탄탄 베이직 자켓 스커트 셋업',
          type: 'jacket',
          price: 35000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/jacket/jk1442/main.gif',
        },
        {
          id: 8,
          code: 'jk1962',
          name: 'jk1962 수술 디테일 포인트의 라운드넥 트위드 자켓',
          type: 'jacket',
          price: 45000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/jacket/jk1962/main.gif',
        },
        {
          id: 9,
          code: 'jk1989',
          name: 'jk1989 고급스러운 버튼 장식의 테일러드 트위드 자켓',
          type: 'jacket',
          price: 42000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/jacket/jk1989/main.gif',
        },
        {
          id: 10,
          code: 'jk2091',
          name: 'jk2091 룩스 바이오워싱 캐쥬얼 루즈핏 자켓',
          type: 'jacket',
          price: 39000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/jacket/jk2091/main.gif',
        },
        {
          id: 11,
          code: 'ts1935',
          name: 'ts1935 12가지의 컬러의 베이직한 맨투맨 티셔츠',
          type: 'shirts',
          price: 39000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/shirts/ts1935/main.gif',
        },
        {
          id: 12,
          code: 'ts2747',
          name: 'ts2747 쫀득한 슬림핏 라운드넥 티셔츠',
          type: 'shirts',
          price: 20000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/shirts/ts2747/main.gif',
        },
        {
          id: 13,
          code: 'ts2967',
          name: 'ts2967 셔링 랩 디자인의 슬림 티셔츠',
          type: 'shirts',
          price: 21000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/shirts/ts2967/main.gif',
        },
        {
          id: 14,
          code: 'ts2985',
          name: 'ts2985 리엘 탄탄소프트 골지 U넥 니트 티셔츠',
          type: 'shirts',
          price: 23000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/shirts/ts2985/main.gif',
        },
        {
          id: 15,
          code: 'ts3097',
          name: 'ts3097 파인트 베이직 라운드넥 루즈핏 맨투맨',
          type: 'shirts',
          price: 25000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/shirts/ts3097/main.gif',
        },
        {
          id: 16,
          code: 'ps3732',
          name: 'ps3732 절개 플레어 디자인의 뒷밴딩 미니 큐롯 팬츠',
          type: 'skirt',
          price: 28000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/skirt/ps3732/main.gif',
        },
        {
          id: 17,
          code: 'ps3800',
          name: 'ps3800 링클 원단의 밴딩 A라인 캉캉 미니 큐롯 팬츠',
          type: 'skirt',
          price: 23000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/skirt/ps3800/main.gif',
        },
        {
          id: 18,
          code: 'sk5413',
          name: 'sk5413 파스텔 컬러 3기장 플레어 스커트',
          type: 'skirt',
          price: 29000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/skirt/sk5413/main.gif',
        },
        {
          id: 19,
          code: 'sk5580',
          name: 'sk5580 뮤제 이염방지 히든밴딩 생지 미니스커트',
          type: 'skirt',
          price: 35000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/skirt/sk5580/main.gif',
        },
        {
          id: 20,
          code: 'sk5592',
          name: 'sk5592 엘리 에나멜 미니 스커트',
          type: 'skirt',
          price: 36000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/skirt/sk5592/main.gif',
        },
        {
          id: 21,
          code: 'op13507',
          name: 'op13507 데이쉬 찰랑핏 베이직 스트랩 미니 셔츠 원피스',
          type: 'dress',
          price: 43000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/dress/op13507/main.gif',
        },
        {
          id: 22,
          code: 'op13547',
          name: 'op13547 세련된 셔츠 배색 미니 원피스',
          type: 'dress',
          price: 45000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/dress/op13547/main.gif',
        },
        {
          id: 23,
          code: 'op13550',
          name: 'op13550 블라썸 쉬폰 플라워 자가드 원피스',
          type: 'dress',
          price: 48000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/dress/op13550/main.gif',
        },
        {
          id: 24,
          code: 'op13561',
          name: 'op13561 클라라 배색 리본 플레어 미니 원피스',
          type: 'dress',
          price: 40000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/dress/op13561/main.gif',
        },
        {
          id: 25,
          code: 'op13616',
          name: 'op13616 로맨틱한 플라워 패턴의 언발셔링 미니 원피스',
          type: 'dress',
          price: 47000,
          dibs: 0,
          perchase_quantity: 0,
          image: '/imgs/Products/dress/op13616/main.gif',
        },
      ])
      .execute();

    //////////// Product

    const ProductsCode = [
      'bs4691',
      'bs5039',
      'bs6704',
      'bs6709',
      'bs6714',
      'jk1296',
      'jk1442',
      'jk1962',
      'jk1989',
      'jk2091',
      'ts1935',
      'ts2747',
      'ts2967',
      'ts2985',
      'ts3097',
      'ps3732',
      'ps3800',
      'sk5413',
      'sk5580',
      'sk5592',
      'op13507',
      'op13547',
      'op13550',
      'op13561',
      'op13616',
    ];

    const types = ['blouse', 'jacket', 'shirts', 'skirt', 'dress'];

    const createData = (type, code, id) => {
      const sub = Array(8)
        .fill(0)
        .map((value, index) => {
          return {
            id: id + index,
            subimage: `/imgs/Products/${type}/${code}/sub${index + 1}.jpg`,
            kind: 'slide',
            code: code,
          };
        });
      const desc = Array(8)
        .fill(0)
        .map((value, index) => {
          return {
            id: id + index + 8,
            subimage: `/imgs/Products/${type}/${code}/desc${index + 1}.jpg`,
            kind: 'desc',
            code: code,
          };
        });
      return sub.concat(desc);
    };

    for (let i = 0; i < ProductsCode.length; i++) {
      await connection
        .createQueryBuilder()
        .insert()
        .into(ProductSubImg)
        .values(
          createData(types[Math.floor(i / 5)], ProductsCode[i], i * 16 + 1),
        )
        .execute();
    }

    ////// ProductSubImg

    await connection
      .createQueryBuilder()
      .insert()
      .into(ProductSailInfo)
      .values([
        {
          id: 1,
          code: 'bs4691',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 2,
          code: 'bs4691',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 3,
          code: 'bs4691',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 4,
          code: 'bs4691',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 5,
          code: 'bs4691',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 6,
          code: 'bs4691',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 7,
          code: 'bs4691',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 8,
          code: 'bs4691',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 9,
          code: 'bs4691',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 10,
          code: 'bs5039',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 11,
          code: 'bs5039',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 12,
          code: 'bs5039',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 13,
          code: 'bs5039',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 14,
          code: 'bs5039',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 15,
          code: 'bs5039',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 16,
          code: 'bs5039',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 17,
          code: 'bs5039',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 18,
          code: 'bs5039',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 19,
          code: 'bs6704',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 20,
          code: 'bs6704',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 21,
          code: 'bs6704',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 22,
          code: 'bs6704',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 23,
          code: 'bs6704',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 24,
          code: 'bs6704',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 25,
          code: 'bs6704',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 26,
          code: 'bs6704',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 27,
          code: 'bs6704',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 28,
          code: 'bs6709',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 29,
          code: 'bs6709',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 30,
          code: 'bs6709',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 31,
          code: 'bs6709',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 32,
          code: 'bs6709',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 33,
          code: 'bs6709',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 34,
          code: 'bs6709',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 35,
          code: 'bs6709',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 36,
          code: 'bs6709',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 37,
          code: 'bs6714',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 38,
          code: 'bs6714',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 39,
          code: 'bs6714',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 40,
          code: 'bs6714',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 41,
          code: 'bs6714',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 42,
          code: 'bs6714',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 43,
          code: 'bs6714',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 44,
          code: 'bs6714',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 45,
          code: 'bs6714',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 46,
          code: 'jk1296',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 47,
          code: 'jk1296',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 48,
          code: 'jk1296',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 49,
          code: 'jk1296',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 50,
          code: 'jk1296',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 51,
          code: 'jk1296',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 52,
          code: 'jk1296',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 53,
          code: 'jk1296',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 54,
          code: 'jk1296',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 55,
          code: 'jk1442',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 56,
          code: 'jk1442',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 57,
          code: 'jk1442',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 58,
          code: 'jk1442',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 59,
          code: 'jk1442',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 60,
          code: 'jk1442',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 61,
          code: 'jk1442',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 62,
          code: 'jk1442',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 63,
          code: 'jk1442',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 64,
          code: 'jk1962',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 65,
          code: 'jk1962',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 66,
          code: 'jk1962',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 67,
          code: 'jk1962',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 68,
          code: 'jk1962',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 69,
          code: 'jk1962',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 70,
          code: 'jk1962',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 71,
          code: 'jk1962',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 72,
          code: 'jk1962',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 73,
          code: 'jk1989',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 74,
          code: 'jk1989',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 75,
          code: 'jk1989',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 76,
          code: 'jk1989',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 77,
          code: 'jk1989',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 78,
          code: 'jk1989',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 79,
          code: 'jk1989',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 80,
          code: 'jk1989',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 81,
          code: 'jk1989',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 82,
          code: 'jk2091',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 83,
          code: 'jk2091',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 84,
          code: 'jk2091',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 85,
          code: 'jk2091',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 86,
          code: 'jk2091',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 87,
          code: 'jk2091',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 88,
          code: 'jk2091',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 89,
          code: 'jk2091',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 90,
          code: 'jk2091',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 91,
          code: 'ts1935',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 92,
          code: 'ts1935',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 93,
          code: 'ts1935',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 94,
          code: 'ts1935',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 95,
          code: 'ts1935',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 96,
          code: 'ts1935',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 97,
          code: 'ts1935',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 98,
          code: 'ts1935',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 99,
          code: 'ts1935',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 100,
          code: 'ts2747',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 101,
          code: 'ts2747',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 102,
          code: 'ts2747',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 103,
          code: 'ts2747',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 104,
          code: 'ts2747',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 105,
          code: 'ts2747',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 106,
          code: 'ts2747',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 107,
          code: 'ts2747',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 108,
          code: 'ts2747',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 109,
          code: 'ts2967',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 110,
          code: 'ts2967',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 111,
          code: 'ts2967',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 112,
          code: 'ts2967',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 113,
          code: 'ts2967',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 114,
          code: 'ts2967',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 115,
          code: 'ts2967',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 116,
          code: 'ts2967',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 117,
          code: 'ts2967',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 118,
          code: 'ts2985',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 119,
          code: 'ts2985',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 120,
          code: 'ts2985',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 121,
          code: 'ts2985',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 122,
          code: 'ts2985',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 123,
          code: 'ts2985',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 124,
          code: 'ts2985',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 125,
          code: 'ts2985',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 126,
          code: 'ts2985',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 127,
          code: 'ts3097',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 128,
          code: 'ts3097',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 129,
          code: 'ts3097',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 130,
          code: 'ts3097',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 131,
          code: 'ts3097',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 132,
          code: 'ts3097',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 133,
          code: 'ts3097',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 134,
          code: 'ts3097',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 135,
          code: 'ts3097',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 136,
          code: 'ps3732',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 137,
          code: 'ps3732',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 138,
          code: 'ps3732',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 139,
          code: 'ps3732',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 140,
          code: 'ps3732',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 141,
          code: 'ps3732',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 142,
          code: 'ps3732',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 143,
          code: 'ps3732',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 144,
          code: 'ps3732',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 145,
          code: 'ps3800',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 146,
          code: 'ps3800',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 147,
          code: 'ps3800',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 148,
          code: 'ps3800',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 149,
          code: 'ps3800',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 150,
          code: 'ps3800',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 151,
          code: 'ps3800',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 152,
          code: 'ps3800',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 153,
          code: 'ps3800',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 154,
          code: 'sk5413',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 155,
          code: 'sk5413',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 156,
          code: 'sk5413',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 157,
          code: 'sk5413',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 158,
          code: 'sk5413',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 159,
          code: 'sk5413',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 160,
          code: 'sk5413',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 161,
          code: 'sk5413',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 162,
          code: 'sk5413',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 163,
          code: 'sk5580',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 164,
          code: 'sk5580',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 165,
          code: 'sk5580',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 166,
          code: 'sk5580',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 167,
          code: 'sk5580',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 168,
          code: 'sk5580',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 169,
          code: 'sk5580',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 170,
          code: 'sk5580',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 171,
          code: 'sk5580',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 172,
          code: 'sk5592',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 173,
          code: 'sk5592',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 174,
          code: 'sk5592',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 175,
          code: 'sk5592',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 176,
          code: 'sk5592',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 177,
          code: 'sk5592',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 178,
          code: 'sk5592',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 179,
          code: 'sk5592',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 180,
          code: 'sk5592',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 181,
          code: 'op13507',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 182,
          code: 'op13507',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 183,
          code: 'op13507',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 184,
          code: 'op13507',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 185,
          code: 'op13507',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 186,
          code: 'op13507',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 187,
          code: 'op13507',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 188,
          code: 'op13507',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 189,
          code: 'op13507',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 190,
          code: 'op13547',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 191,
          code: 'op13547',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 192,
          code: 'op13547',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 193,
          code: 'op13547',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 194,
          code: 'op13547',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 195,
          code: 'op13547',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 196,
          code: 'op13547',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 197,
          code: 'op13547',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 198,
          code: 'op13547',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 199,
          code: 'op13550',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 200,
          code: 'op13550',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 201,
          code: 'op13550',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 202,
          code: 'op13550',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 203,
          code: 'op13550',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 204,
          code: 'op13550',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 205,
          code: 'op13550',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 206,
          code: 'op13550',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 207,
          code: 'op13550',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 208,
          code: 'op13561',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 209,
          code: 'op13561',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 210,
          code: 'op13561',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 211,
          code: 'op13561',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 212,
          code: 'op13561',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 213,
          code: 'op13561',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 214,
          code: 'op13561',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 215,
          code: 'op13561',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 216,
          code: 'op13561',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 217,
          code: 'op13616',
          color: 'Red',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 218,
          code: 'op13616',
          color: 'Red',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 219,
          code: 'op13616',
          color: 'Red',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 220,
          code: 'op13616',
          color: 'White',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 221,
          code: 'op13616',
          color: 'White',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 222,
          code: 'op13616',
          color: 'White',
          size: 'L',
          quantity: 9999,
        },
        {
          id: 223,
          code: 'op13616',
          color: 'Black',
          size: 'S',
          quantity: 9999,
        },
        {
          id: 224,
          code: 'op13616',
          color: 'Black',
          size: 'M',
          quantity: 9999,
        },
        {
          id: 225,
          code: 'op13616',
          color: 'Black',
          size: 'L',
          quantity: 9999,
        },
      ])
      .execute();

    /////// ProductSailInfo
  }
}
